[package]
name = "impg"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.0", features = ["derive"] }
coitrees = "0.4.0"
num_cpus = "1.16.0"
rayon = "1.9.0"
serde = { version = "1.0.197", features = ["derive"] }
noodles = { version = "0.66.0", features = ["bgzf"] }
regex = "1.10.4"
itertools = "0.13.0"
